CREATE OR REPLACE MODEL
  [DATASET].modelo_tarifa OPTIONS( MODEL_TYPE = 'LINEAR_REG',
    CATEGORY_ENCODING_METHOD = 'ONE_HOT_ENCODING',
    ENABLE_GLOBAL_EXPLAIN = TRUE,
    INPUT_LABEL_COLS = ['c_monto_tarifa'],
    DATA_SPLIT_METHOD = 'RANDOM',
    DATA_SPLIT_EVAL_FRACTION = 0.3) AS
SELECT
  * except (tgt_propina_sup_20)
FROM
  `[PROJECT_ID].[DATASET].tad_propina`;
